### ISSUE TITLE
Functions.php: Get rid of the wp-tuts

### ISSUE THREAD

**Issue by rcass** [redacademy/wild-spring-2018#12]
So in your functions.php there are LOTS of enqueue scripts and styles. I think there needs to be some reorganization in that area, just so it is easier to manage/read.

Here are some ideas:
1) **Remove the duplicate add_action** - Currently you have two `add_action( 'wp_enqueue_scripts' ....` but really you just need one. You can move everything from the `wptuts_enqueue()` into the starter scripts. 
Also I know they are registering then enqueue, but I recommend changing the way those are written to match the syntax or your scripts and styles. 
2) **Add jQuery enqueue** - `wp_enqueue_script('jquery');`  https://wordpress.stackexchange.com/questions/140307/is-jquery-included-in-wordpress-by-default
3) **All needed?**  - You have a LOT of script files, but I am not sure if all of them are needed. Maybe take a moment and see if any should be in the same file or just deleted.

**Comment by pinaska** [comment]
wp-tuts removed
