### ISSUE TITLE
<a> tag not allowed as child of <ul>

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/wild-spring-2018#2]
<ul> tag direct child elements should only ever be <li> elements.
You can of course add <a> tags inside of the <li> however you should never wrap <li> tags with other elements as it's not valid markup.

Change: ``` echo('<a href="tag/'.$tag->slug.'"><li> #'.$tag->name.'</li></a>');```
to: ``` echo('<li><a href="tag/'.$tag->slug.'">#'.$tag->name.'</a></li>');```
or something like that

https://github.com/redacademy/wild-spring-2018/blob/8ccdd4f6db6f0e06f57f2ff812658b25f9903601/themes/wav-theme/page-templates/front-page.php#L92

**Comment by pinaska** [comment]
changed
