### ISSUE TITLE
Functions.php: Move to include files

### ISSUE THREAD

**Issue by rcass** [redacademy/wild-spring-2018#20]
The functions.php is getting a little large and unorganized.

Towards the end of the file I noticed these functions:
https://github.com/redacademy/wild-spring-2018/blob/a2c2fb8035cfc715b60071de8fe96b8442f6ac09/themes/wav-theme/functions.php#L151-L184

I would move these to extras.php instead to make things more organized

**Comment by pinaska** [comment]
Code moved to separate file. Thank you.
