### ISSUE TITLE
Unnecessary Page Template

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/wild-spring-2018#3]
With the WordPress template hierarchy front-page.php will be loaded for the front page of the site if the file exists. You shouldn't have to add the comment block at the top to assign a page this template. Instead you should just set the page you want in the dashboard settings, then you can remove the comment block and move the template file front-page.php from the subfolder to the root directory

https://github.com/redacademy/wild-spring-2018/blob/9d94daedf9a9a3ffa4851c33aa37d4351cf69061/themes/wav-theme/page-templates/front-page.php#L3

**Comment by pinaska** [comment]
item cleared and closed
