### ISSUE TITLE
Front-page: Fix HTML Validation Errors

### ISSUE THREAD

**Issue by rcass** [redacademy/wild-spring-2018#6]
On the front page, I viewed the page source and then put it in the html validator(https://validator.w3.org/#validate_by_input)

There are quite a few errors to resolve, such as:
![screen shot 2018-06-21 at 3 25 20 pm](https://user-images.githubusercontent.com/5028555/41748693-cec1fc7e-7567-11e8-937c-f8cd732699f3.png)
![screen shot 2018-06-21 at 10 01 11 am](https://user-images.githubusercontent.com/5028555/41748729-f6b0e790-7567-11e8-8cbc-b0819c838a32.png)
![screen shot 2018-06-21 at 10 03 08 am](https://user-images.githubusercontent.com/5028555/41748737-f9e16674-7567-11e8-8c8b-d1fe7304f539.png)

## TO DO

- [ ] Fix all HTML validation errors for the front page

**Comment by pinaska** [comment]
I fixed more of the posted errors, not touching tamwood ones.
